DROP TABLE IF EXISTS `V_DATACENTER_MONITOR_INFO_KSH`;

CREATE TABLE `V_DATACENTER_MONITOR_INFO_KSH`
(
    `ADDUP_CYCLE` BIGINT(20),
    `TOTAL_COUNT` BIGINT(20),
    `SUCCESS_QUANTITY` BIGINT(20),
    `ACCESS_SERVICE_NAME` VARCHAR(255),
    `SERVICE_STATUS` VARCHAR(20) ,
    `SERVICE_STATUS_DESCRIPTION` VARCHAR(4000)
);

INSERT INTO V_DATACENTER_MONITOR_INFO_KSH (ADDUP_CYCLE,TOTAL_COUNT,SUCCESS_QUANTITY,ACCESS_SERVICE_NAME,SERVICE_STATUS,SERVICE_STATUS_DESCRIPTION) VALUES
(20240221,287,287,'游客预约及实际入园人数_巡检','SUCCESS','正常');

INSERT INTO V_DATACENTER_MONITOR_INFO_KSH (ADDUP_CYCLE,TOTAL_COUNT,SUCCESS_QUANTITY,ACCESS_SERVICE_NAME,SERVICE_STATUS,SERVICE_STATUS_DESCRIPTION) VALUES
(20240319,0,0,'测试','SUCCESS','正常');
