spring:
  #  动态数据库的设置
  datasource:
    dynamic:
      primary: business
      datasource:
        business:
          driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
          url: jdbc:shardingsphere:classpath:sharding-dev.yaml
        dataOracle:
          username: sa
          password: ""
          url: jdbc:h2:mem:ccic_sync_analog_data;MODE=Oracle;INIT=RUNSCRIPT FROM 'classpath:db/oracle.sql'
          driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: HikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1